name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  tests_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check for changes
      - uses: actions/checkout@v2

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: | 
            cd PythonProjects/spanish_cards_bot
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            ./restart_bot.sh